name: k1s
description: A server app using the shelf package and Docker.
version: 1.0.0
repository: https://github.com/hyprusr/k1s

environment:
  sdk: ^3.9.0

dependencies:
  toml: ^0.16.0
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
